// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Informedica.GenUnits.Lib")>]
[<assembly: AssemblyProductAttribute("GenUnits")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-20T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ff6dab30b102f2b4fc52137db9930442c0311616")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Informedica.GenUnits.Lib"
    let [<Literal>] AssemblyProduct = "GenUnits"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-20T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
    let [<Literal>] AssemblyInformationalVersion = "1.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ff6dab30b102f2b4fc52137db9930442c0311616"
