
#r "nuget: MathNet.Numerics.FSharp"

#load "../Continuation.fs"
#load "../Memoization.fs"
#load "../Reflection.fs"
#load "../NullCheck.fs"
#load "../BCL/Char.fs"
#load "../BCL/String.fs"
#load "../BCL/Int32.fs"
#load "../BCL/Double.fs"
#load "../BCL/BigInteger.fs"
#load "../BCL/BigRational.fs"
#load "../BCL/Decimal.fs"
#load "../BCL/DateTime.fs"
#load "../Option.fs"
#load "../StringBuilder.fs"
#load "../Array.fs"
#load "../List.fs"
#load "../Seq.fs"
#load "../Path.fs"
#load "../File.fs"
#load "../Csv.fs"
#load "../Env.fs"
#load "../App.fs"